# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KalenStudyProject' do

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MMPlaceHolder', '~> 1.8'
pod 'jastor', '~> 0.2.1'
pod 'MJRefresh', '~> 2.3.2'
pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MMDrawerController', '~> 0.6.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'MMDrawerController', '~> 0.6.0'
pod 'FMDB', '~> 2.5'
pod 'Masonry', '~> 0.6.2'
end

target 'KalenStudyProjectTests' do
pod 'FMDB', '~> 2.5'
end

target 'KalenStudyProjectUITests' do

end

